### ISSUE TITLE
Replicator should not stop by missing revisions

### ISSUE THREAD

**Issue by hideki** [couchbase/couchbase-lite-java-core#728]
https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L314

Requested revision might not exist on the server. And Sync Gateway returns error. in this error case, the client should not stop replicator.

**Comment by NitzDKoder** [comment]
@hideki Pls confirm if this below logs points to the same puller issue? When can we expect the fix? Do we need to start the puller again in this case? pls advice

[11/23 09:02:34.041] [13] Sync: downloadsToInsert.waitForPendingFutures()
[11/23 09:02:34.043] [13] Sync: [fireTrigger()] => WAITING_FOR_CHANGES
[11/23 09:02:34.047] [3] Sync: firing trigger: WAITING_FOR_CHANGES
[11/23 09:02:34.049] [3] Sync: [onEntry()] RUNNING => IDLE
[11/23 09:02:34.051] [3] Sync: State transition: RUNNING -> IDLE (via WAITING_FOR_CHANGES).  this: com.couchbase.lite.replicator.PullerInternal@1568dbe6
[11/23 09:02:34.053] [3] Sync: IDLE: triggerStop() com.couchbase.lite.CouchbaseLiteException
[11/23 09:02:34.052] [13] Sync: [waitForPendingFutures()] END - thread id: 5855
[11/23 09:02:34.058] [3] Sync: [fireTrigger()] => STOP_GRACEFUL
[011/23 09:002:34.060] [3] Sync: firing trigger: STOP_GRACEFUL
[11/23 09:02:34.062] [3] Sync: [onExit()] IDLE => STOPPING
[11/23 09:02:34.064] [3] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PullerInternal@1568dbe6
[11/23 09:02:34.066] [3] Sync: [onExit()] IDLE => STOPPING
[11/23 09:02:34.068] [3] Sync: [onEntry()] IDLE => STOPPING
[11/23 09:02:34.070] [3] Sync: stopGraceful()
[11/23 09:02:34.071] [3] Sync: PullerInternal.stopGraceful() started
[11/23 09:02:34.075] [3] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PullerInternal@1568dbe6
[11/23 09:02:34.077] [19] Sync: stopping change tracker
[11/23 09:02:34.079] [19] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@31a34079: Changed tracker asked to stop
[11/23 09:02:34.080] [19] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@31a34079: Changed tracker aborting request: org.apache.http.client.methods.HttpPost@2d2e18f8
[11/23 09:02:34.083] [19] Sync: stopped change tracker
[11/23 09:02:34.083] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@31a34079: Change tracker run loop exiting
[11/23 09:02:34.084] [19] Sync: [fireTrigger()] => STOP_IMMEDIATE
[11/23 09:02:34.085] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@31a34079: Change tracker in stopped()
[11/23 09:02:34.085] [19] Sync: PullerInternal stopGraceful.run() finished
[11/23 09:002:34.086] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@31a34079: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@1568dbe6
[11/23 09:02:34.087] [3] Sync: firing trigger: STOP_IMMEDIATE
[11/23 09:02:34.089] [3] Sync: [onEntry()] STOPPING => STOPPED
[11/23 09:02:34.091] [3] Sync: com.couchbase.lite.replicator.PullerInternal@1568dbe6: saveLastSequence() called. lastSequence: 384388 remoteCheckpoint: null
[11/23 09:02:34.094] [3] Sync: com.couchbase.lite.replicator.PullerInternal@1568dbe6: start put remote _local document.  checkpointID: 75fbbc752adcf39fc1be400480987faaf7e8bf01 body: {lastSequence=384388}
[11/23 09:02:34.096] [3] Sync: [sendAsyncRequest()] PUT => https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.097] [3] Sync: com.couchbase.lite.support.RemoteRequestRetry@100c61d1: RemoteRequestRetry created, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.098] [3] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest created, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.100] [3] Sync: [fireTrigger()] => RESUME
[11/23 09:02:34.100] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest run() called, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:034.101] [3] Sync: com.couchbase.lite.replicator.PullerInternal@1568dbe6: clearDbRef() called
[11/23 09:02:34.102] [20] Sync: [PullerInternal.waitForPendingFutures()] STARTED - thread id: 5905
[11/023 009:002:034.102] [3] CBLite: com.couchbase.lite.Database[/data/data/com.xyz.ui/files/dbdata.cblite]: setLastSequence() called with lastSequence: 384388 checkpointId: 75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.102] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest calling httpClient.execute, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.103] [20] Sync: batcher.waitForPendingFutures()
[11/23 09:02:34.106] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest calling httpClient.execute, client: org.apache.http.impl.client.DefaultHttpClient@1aa7cca4 url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.106] [20] Sync: waitPendingFuturesCompleted()
[11/23 09:02:34.110] [20] Sync: calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@100c61d1
[11/23 09:02:34.116] [3] Sync: com.couchbase.lite.replicator.PullerInternal@1568dbe6: clearDbRef() setting db to null
[11/23 09:02:34.205] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest called httpClient.execute, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.209] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest finally block.  url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.210] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest calling respondWithResult.  url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01, error: null
[11/23 09:02:34.211] [15] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@260447d3: RemoteRequestRetry inner request finished, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.212] [15] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@260447d3: RemoteRequestRetry was successful, calling callback url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.213] [15] Sync: com.couchbase.lite.replicator.ReplicationInternal$7@1de70f10: put remote _local document request finished.  checkpointID: 75fbbc752adcf39fc1be400480987faaf7e8bf01 body: {lastSequence=384388}
[11/23 09:02:34.214] [15] Sync: com.couchbase.lite.replicator.ReplicationInternal$7@1de70f10: Database is null or closed, not calling db.setLastSequence() 
[11/23 09:02:34.215] [15] Sync: com.couchbase.lite.support.RemoteRequest@13b98436: RemoteRequest run() finished, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/75fbbc752adcf39fc1be400480987faaf7e8bf01
[11/23 09:02:34.216] [20] Sync: done calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@100c61d1
[11/23 09:02:34.217] [20] Sync: downloadsToInsert.waitForPendingFutures()
[11/23 09:02:34.218] [20] Sync: [fireTrigger()] => WAITING_FOR_CHANGES
[11/23 09:02:34.218] [3] Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: com.couchbase.lite.replicator.PullerInternal@1568dbe6
[11/23 09:02:034.219] [20] Sync: [waitForPendingFutures()] END - thread id: 5905
[11/023 09:02:34.220] [3] Sync: changeTrackerStopped.  lifecycle: CONTINUOUS
[11/23 09:02:34.220] [3] Sync: Change tracker stopped because replicator is stopping or stopped.
[11/23 09:02:34.221] [3] Sync: firing trigger: RESUME
[11/23 09:02:34.222] [3] Sync: firing trigger: WAITING_FOR_CHANGES
[11/23 09:02:35.210] [0] Database: main Begin transaction (level 0)

thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,

This issue should be fixed by v1.2.0 release. 

From your log information, I can not suspect why replicator stopped. Could you debug into replicator code?

Thanks!

**Comment by NitzDKoder** [comment]
@hideki sure will try to debug..Pls check new logs..
[11/24 12:53:27.072] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: finished inserting 1 revisions
[11/24 12:53:27.072] [3] Database: CBLManagerWorkExecutor Committing transaction (level 0)
[11/24 12:53:27.088] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: Setting lastSequence to 400595::402752 from(400595::402736)
[11/24 12:53:27.089] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: inserted 1 revs in 25 milliseconds
[11/24 12:53:27.089] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578 insertDownloads() updating completedChangesCount from 60 -> 61 
[11/24 12:53:27.090] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: Incrementing completedChangesCount count from 60 by adding 1 -> 61
[11/24 12:53:27.090] [3] CBLite: setPaused: false
[11/24 12:53:27.091] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@211f7c0b
[11/24 12:53:27.092] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2db55ae8
[11/24 12:53:27.092] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.093] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.094] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.094] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.097] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.094] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2db55ae8
[11/24 12:53:27.098] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 012:53:27.099] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f5a9501
[11/24 12:53:27.099] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 012:53:27.100] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f5a9501
[11/024 12:53:27.100] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.101] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.100] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@a47cde7
[11/24 12:53:27.102] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.102] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@a47cde7
[11/24 12:53:27.103] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.104] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.105] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.105] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.106] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.106] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.107] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.108] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.108] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.109] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.109] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.110] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.111] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.111] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.103] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@28f93d94
[011/24 012:53:27.114] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.114] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@28f93d94
[11/24 12:53:27.114] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.114] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@175a803d
[011/24 12:53:27.115] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.116] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@175a803d
[11/24 12:53:27.116] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3df69f00
[11/24 12:53:27.117] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3df69f00
[11/24 12:53:27.118] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@73e339
[11/24 12:53:27.118] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@73e339
[11/24 12:53:27.115] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@37a94d7e
[11/24 012:53:27.119] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.119] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@37a94d7e
[11/24 012:53:27.120] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.120] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@362692df
[11/24 12:053:27.120] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.121] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@362692df
[11/24 12:53:27.121] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.121] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6a6ab2c
[11/24 12:053:27.122] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.122] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6a6ab2c
[11/24 12:53:27.123] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2d2679f5
[11/24 12:53:27.124] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2d2679f5
[11/24 12:53:27.124] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3b08c38a
[11/24 12:53:27.125] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3b08c38a
[11/24 12:53:27.126] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@150b7dfb
[11/24 12:53:27.127] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@150b7dfb
[11/24 12:53:27.127] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@e31c071
[11/24 12:53:27.128] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@e31c071
[11/24 12:53:27.130] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c378e56
[11/24 12:53:27.131] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c378e56
[11/24 12:53:27.132] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d89fed7
[11/24 12:53:27.133] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d89fed7
[11/24 12:53:27.133] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@30b133c4
[11/24 12:53:27.145] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.146] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.146] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@30b133c4
[11/24 12:53:27.148] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6d0f2ad
[11/24 12:53:27.199] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.200] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.201] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6d0f2ad
[11/24 12:53:27.201] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2fb639e2
[11/24 12:53:27.258] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.259] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.260] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2fb639e2
[11/24 12:53:27.260] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d05b173
[11/24 12:53:27.338] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.339] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.341] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3d05b173
[11/24 12:53:27.342] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@296fc830
[11/24 12:53:27.421] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.423] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.427] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@296fc830
[11/24 12:53:27.429] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@38b70ca9
[11/24 12:53:27.491] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.493] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.496] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@38b70ca9
[11/24 12:53:27.499] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f82122e
[11/24 12:53:27.567] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.569] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.573] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f82122e
[11/24 12:53:27.575] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@97ff1cf
[11/24 12:53:27.629] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.631] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.634] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@97ff1cf
[11/24 12:53:27.636] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2621233a
[11/24 12:53:27.696] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.698] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.700] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2621233a
[11/24 12:53:27.702] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f2b15f4
[11/24 12:53:27.792] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.794] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.800] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f2b15f4
[11/24 12:53:27.803] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@24c0e11d
[11/24 12:53:27.888] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.890] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.891] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@24c0e11d
[11/24 12:53:27.893] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2424df92
[11/24 12:53:27.976] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:27.978] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:27.980] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2424df92
[11/24 12:53:27.982] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1cbddd63
[11/24 12:53:28.060] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called
[11/24 12:53:28.062] [3] Batcher: com.couchbase.lite.support.Batcher@25904f08: processNow() called, but inbox is empty
[11/24 12:53:28.064] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1cbddd63
[11/24 12:53:28.066] [13] Batcher: com.couchbase.lite.support.Batcher@25904f08: /waitForPendingFutures
[11/24 12:53:28.068] [13] Batcher: com.couchbase.lite.support.Batcher@f22148e: delayToUse() delta: 2865, delayToUse: 0, delayMs: 500
[11/24 12:53:28.070] [13] Sync: batcher.waitForPendingFutures()
[11/24 12:53:28.072] [13] Batcher: com.couchbase.lite.support.Batcher@f22148e: waitForPendingFutures
[11/24 12:53:28.077] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@216d699
[11/24 12:53:28.079] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@216d699
[11/24 12:53:28.081] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29808a36
[11/24 12:53:28.083] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29808a36
[11/24 12:53:28.085] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1785e510
[11/24 12:53:28.087] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1785e510
[11/24 12:53:28.096] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2df3591a
[11/24 12:53:28.097] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2df3591a
[11/24 12:53:28.098] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@19102227
[11/24 12:53:28.099] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@19102227
[11/24 12:53:28.100] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@17a4b240
[11/24 12:53:28.101] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@17a4b240
[11/24 12:53:28.102] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@28e43cca
[11/24 12:53:28.113] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@28e43cca
[11/24 12:53:28.115] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33df9b22
[11/24 12:53:28.116] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33df9b22
[11/24 12:53:28.117] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9a3cee9
[11/24 12:53:28.118] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@9a3cee9
[11/24 12:53:28.119] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@13f61e0f
[11/24 12:53:28.120] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@13f61e0f
[11/24 12:53:28.121] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@356170a5
[11/24 12:53:28.122] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@356170a5
[11/24 12:53:28.125] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f6d6c7a
[11/24 12:53:28.125] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2f6d6c7a
[11/24 12:53:28.126] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29d7221
[11/24 12:53:28.127] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29d7221
[11/24 12:53:28.128] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c55d646
[11/24 12:53:28.129] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3c55d646
[11/24 12:53:28.130] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@17f9c007
[11/24 12:53:28.131] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@17f9c007
[11/24 12:53:28.132] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1a431534
[11/24 12:53:28.133] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1a431534
[11/24 12:53:28.134] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@393e0f5d
[11/24 12:53:28.135] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@393e0f5d
[11/24 12:53:28.136] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@70910d2
[11/24 12:53:28.137] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@70910d2
[11/24 12:53:28.138] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@166855a3
[11/24 12:53:28.142] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@166855a3
[11/24 12:53:28.144] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@339650a0
[11/24 12:53:28.145] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@339650a0
[11/24 12:53:28.146] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3f514459
[11/24 12:53:28.147] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3f514459
[11/24 12:53:28.148] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e43681e
[11/24 12:53:28.148] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e43681e
[11/24 12:53:28.149] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@21a0a8ff
[11/24 12:53:28.150] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@21a0a8ff
[11/24 12:53:28.151] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@391fd6cc
[11/24 12:53:28.151] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@391fd6cc
[11/24 12:53:28.152] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33c8cd15
[11/24 12:53:28.153] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@33c8cd15
[11/24 12:53:28.154] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e39e82a
[11/24 12:53:28.154] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e39e82a
[11/24 12:53:28.155] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@de0d61b
[11/24 12:53:28.161] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@de0d61b
[11/24 12:53:28.162] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1dd993b8
[11/24 12:53:28.162] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1dd993b8
[11/24 12:53:28.163] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@38f62591
[11/24 12:53:28.164] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@38f62591
[11/24 12:53:28.165] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f665cf6
[11/24 12:53:28.166] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f665cf6
[11/24 12:53:28.166] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2b2cb8f7
[11/24 12:53:28.167] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2b2cb8f7
[11/24 12:53:28.168] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8703364
[11/24 12:53:28.168] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8703364
[11/24 12:53:28.170] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2ac689cd
[11/24 12:53:28.170] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2ac689cd
[11/24 12:53:28.171] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16135282
[11/24 12:53:28.172] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16135282
[11/24 12:53:28.174] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1be9ed93
[11/24 12:53:28.175] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1be9ed93
[11/24 12:53:28.176] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3baf21d0
[11/24 12:53:28.177] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3baf21d0
[11/24 12:53:28.178] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3cbef5c9
[11/24 12:53:28.179] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3cbef5c9
[11/24 12:53:28.180] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2ea814ce
[11/24 12:53:28.181] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2ea814ce
[11/24 12:53:28.181] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@393bcfef
[11/24 12:53:28.182] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@393bcfef
[11/24 12:53:28.183] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@19ac8afc
[11/24 12:53:28.184] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@19ac8afc
[11/24 12:53:28.185] [13] Batcher: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3bb82585
[11/24 12:53:28.186] [13] Batcher: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3bb82585
[11/24 12:53:28.187] [13] Batcher: com.couchbase.lite.support.Batcher@f22148e: /waitForPendingFutures
[11/24 12:53:28.187] [13] Sync: waitPendingFuturesCompleted()
[11/24 12:53:28.188] [13] Sync: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@338f7219
[11/24 12:53:28.189] [13] Sync: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@338f7219
[11/24 12:53:28.192] [13] Sync: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@12d62de
[11/24 12:53:28.193] [13] Sync: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@12d62de
[11/24 12:53:28.193] [13] Sync: calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2a26ecbf
[11/24 12:53:28.194] [13] Sync: done calling future.get() on java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2a26ecbf
[11/24 12:53:28.196] [13] Batcher: com.couchbase.lite.support.Batcher@25904f08: delayToUse() delta: 1105, delayToUse: 0, delayMs: 1000
[11/24 12:53:28.196] [13] Sync: downloadsToInsert.waitForPendingFutures()
[11/24 12:53:28.197] [13] Batcher: com.couchbase.lite.support.Batcher@25904f08: waitForPendingFutures
[11/24 12:53:28.198] [13] Batcher: com.couchbase.lite.support.Batcher@25904f08: /waitForPendingFutures
[11/24 12:53:28.199] [13] Sync: [fireTrigger()] => WAITING_FOR_CHANGES
[11/24 12:53:28.200] [13] Sync: [waitForPendingFutures()] END - thread id: 8524
[011/24 12:53:28.200] [3] Sync: firing trigger: WAITING_FOR_CHANGES
[11/24 12:53:28.201] [3] Sync: [onEntry()] RUNNING => IDLE
[11/24 12:53:28.202] [3] Sync: State transition: RUNNING -> IDLE (via WAITING_FOR_CHANGES).  this: com.couchbase.lite.replicator.PullerInternal@2465a578
[11/24 12:53:28.204] [3] Sync: IDLE: triggerStop() com.couchbase.lite.CouchbaseLiteException
[11/24 12:53:28.205] [3] Sync: [fireTrigger()] => STOP_GRACEFUL
[11/24 12:53:28.208] [3] Sync: firing trigger: STOP_GRACEFUL
[11/24 12:53:28.209] [3] Sync: [onExit()] IDLE => STOPPING
[11/24 12:53:28.210] [3] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PullerInternal@2465a578
[11/24 12:53:28.211] [3] Sync: [onExit()] IDLE => STOPPING
[11/24 12:53:28.212] [3] Sync: [onEntry()] IDLE => STOPPING
[11/24 12:53:28.213] [3] Sync: stopGraceful()
[11/24 12:53:28.214] [3] Sync: PullerInternal.stopGraceful() started
[11/24 12:53:28.215] [3] Sync: State transition: IDLE -> STOPPING (via STOP_GRACEFUL).  this: com.couchbase.lite.replicator.PullerInternal@2465a578
[11/24 12:53:28.216] [19] Sync: stopping change tracker
[11/24 12:53:28.217] [19] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@13278653: Changed tracker asked to stop
[11/24 12:53:28.218] [19] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@13278653: Changed tracker aborting request: org.apache.http.client.methods.HttpPost@296f2f8c
[11/24 12:53:28.227] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@13278653: Change tracker run loop exiting
[11/24 12:53:28.229] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@13278653: Change tracker in stopped()
[11/24 12:53:28.229] [19] Sync: stopped change tracker
[11/24 12:53:028.229] [14] ChangeTracker: com.couchbase.lite.replicator.ChangeTracker@13278653: Change tracker calling changeTrackerStopped, client: com.couchbase.lite.replicator.PullerInternal@2465a578
[11/24 12:53:28.230] [19] Sync: [fireTrigger()] => STOP_IMMEDIATE
[11/24 12:53:28.231] [3] Sync: changeTrackerStopped.  lifecycle: CONTINUOUS
[11/24 12:53:28.233] [19] Sync: PullerInternal stopGraceful.run() finished
[11/24 12:53:28.234] [3] Sync: Change tracker stopped because replicator is stopping or stopped.
[11/24 12:53:28.235] [3] Sync: firing trigger: STOP_IMMEDIATE
[11/24 12:53:28.236] [3] Sync: [onEntry()] STOPPING => STOPPED
[11/24 12:53:28.236] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: saveLastSequence() called. lastSequence: 400595::402752 remoteCheckpoint: null
[11/24 12:53:28.237] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: start put remote _local document.  checkpointID: c36db51c94120c6fc6f9444fde4771e436414c59 body: {lastSequence=400595::402752}
[11/24 12:53:28.241] [3] Sync: [sendAsyncRequest()] PUT => https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.242] [3] Sync: com.couchbase.lite.support.RemoteRequestRetry@171c16d5: RemoteRequestRetry created, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.243] [3] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest created, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.244] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest run() called, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.246] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest calling httpClient.execute, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.247] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest calling httpClient.execute, client: org.apache.http.impl.client.DefaultHttpClient@4a5b878 url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.247] [3] Sync: [fireTrigger()] => RESUME
[11/24 12:53:28.249] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: clearDbRef() called
[11/24 12:53:28.250] [3] CBLite: com.couchbase.lite.Database[/data/data/com.xyz.ui/files/dbdata.cblite]: setLastSequence() called with lastSequence: 400595::402752 checkpointId: c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.253] [20] Sync: [PullerInternal.waitForPendingFutures()] STARTED - thread id: 8555
[11/24 12:53:28.257] [20] Batcher: com.couchbase.lite.support.Batcher@f22148e: delayToUse() delta: 3054, delayToUse: 0, delayMs: 500
[11/24 12:53:28.258] [20] Sync: batcher.waitForPendingFutures()
[11/24 12:53:28.259] [20] Batcher: com.couchbase.lite.support.Batcher@f22148e: waitForPendingFutures
[11/24 12:53:28.260] [20] Batcher: com.couchbase.lite.support.Batcher@f22148e: /waitForPendingFutures
[11/24 12:53:28.261] [20] Sync: waitPendingFuturesCompleted()
[11/24 12:53:28.262] [20] Sync: calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@171c16d5
[11/24 12:53:28.265] [3] Sync: com.couchbase.lite.replicator.PullerInternal@2465a578: clearDbRef() setting db to null
[11/24 12:53:28.283] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest called httpClient.execute, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.285] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest finally block.  url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.286] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest calling respondWithResult.  url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59, error: null
[11/24 12:53:28.287] [17] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@363fb4b7: RemoteRequestRetry inner request finished, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.288] [17] Sync: com.couchbase.lite.support.RemoteRequestRetry$1@363fb4b7: RemoteRequestRetry was successful, calling callback url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.291] [17] Sync: com.couchbase.lite.replicator.ReplicationInternal$7@3eb9e424: put remote _local document request finished.  checkpointID: c36db51c94120c6fc6f9444fde4771e436414c59 body: {lastSequence=400595::402752}
[11/24 12:53:28.292] [17] Sync: com.couchbase.lite.replicator.ReplicationInternal$7@3eb9e424: Database is null or closed, not calling db.setLastSequence() 
[11/24 12:53:28.293] [17] Sync: com.couchbase.lite.support.RemoteRequest@23a8ceea: RemoteRequest run() finished, url: https://user1:xyz@bsyncg.xyzhsqc.com:443/dbdata/_local/c36db51c94120c6fc6f9444fde4771e436414c59
[11/24 12:53:28.294] [20] Sync: done calling future.get() on com.couchbase.lite.support.RemoteRequestRetry@171c16d5
[11/24 12:53:28.295] [20] Batcher: com.couchbase.lite.support.Batcher@25904f08: delayToUse() delta: 1204, delayToUse: 0, delayMs: 1000
[11/24 12:53:28.296] [20] Sync: downloadsToInsert.waitForPendingFutures()
[11/24 12:53:28.297] [20] Batcher: com.couchbase.lite.support.Batcher@25904f08: waitForPendingFutures
[11/24 12:53:28.297] [3] Sync: State transition: STOPPING -> STOPPED (via STOP_IMMEDIATE).  this: [11/24 12:53:28.298] [20] Batcher: com.couchbase.lite.support.Batcher@25904f08: /waitForPendingFutures
[11/24 12:53:28.298] [3] Sync: firing trigger: RESUMEcom.couchbase.lite.replicator.PullerInternal@2465a578

**Comment by NitzDKoder** [comment]
@hideki 
1)Found that client was trying to fetch missing rev document from server.
2)When replication encounters 404 does not stop immediately ,replication syncs all the available docs and when it goes to idle its getting stopped.



     // #352 
            // iOS version: stop replicator immediately when call setError() with permanent error. 
            // But, for Core Java, some of codes wait IDLE state. So this is reason to wait till 
            // state becomes IDLE. 
            if(Utils.isPermanentError(error) && isContinuous()){ 
                Log.d(Log.TAG_SYNC, "IDLE: triggerStop() " + error.toString());
                triggerStop(); 
            } 
"// But, for Core Java, some of codes wait IDLE state. So this is reason to wait till 
            // state becomes IDLE."

Thats how the java code work?


[11/24 04:04:08.905] [16] Sync: Error pulling remote revision
org.apache.http.client.HttpResponseException: Not Found
	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.executeRequest(RemoteMultipartDownloaderRequest.java:78)
	at com.couchbase.lite.support.RemoteMultipartDownloaderRequest.run(RemoteMultipartDownloaderRequest.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

[11/24 04:04:08.925] [16] Sync: com.couchbase.lite.replicator.PullerInternal@f844e5c: giving up on {suser1_user.doc #206-ece64064c27345069c5da614f015dec6}: org.apache.http.client.HttpResponseException: Not Found

Thanks
Nithin

**Comment by hideki** [comment]
@NitzDKoder,

Honestly speak, CBL Java/Android does not handle all error scenarios correctly. And, to avoid early replication give up, CBL Java/Android keeps trying to replicate all docs till its state becomes IDLE. We need to fix issue one by one.

404 for particular revision could be happened. Replication should not be stopped by it.

**Comment by NitzDKoder** [comment]
@hideki pls confirm if this fixed in master branch?
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PusherInternal.java

I see major change in this class..
do not find https://github.com/couchbase/couchbase-lite-java-core/blob/release/1.1.0/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L314

Just want to run on our issue..

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,
I am not sure what your question is. First one is PusherInternal.java (code for push replication) and second one is PullerInternal.java (code for pull replication).
Could you please update your question?

**Comment by NitzDKoder** [comment]
@hideki wrong links were posted..pls see question updated..

**Comment by hideki** [comment]
Hi @NitzDKoder,

I believe this issue is not fixed yet.

You could fix this by modifying `Utils.isTransientError()` or `PullerInternal.revisionFailed()`
https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/replicator/PullerInternal.java#L583

https://github.com/couchbase/couchbase-lite-java-core/blob/master/src/main/java/com/couchbase/lite/util/Utils.java#L71

**Comment by hideki** [comment]
related ticket: #723

**Comment by hideki** [comment]
Jenkins Project URL http://qa.sc.couchbase.com/view/mobile/job/sync-gateway-mobile-functional-tests-android-cb
